server:
  port: 8001

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    ip-address: 127.0.0.1
    instance-id: provider-hystrix-8001
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2

spring:
  application:
    name: provider-hystrix-8001
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    # MySQL驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mmp?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: userMagi
    password: admin

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.entities
